// Copyright 2020 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// ** This file is automatically generated by gapic-generator-typescript. **
// ** https://github.com/googleapis/gapic-generator-typescript **
// ** All changes to this file may be overwritten. **

import * as protosTypes from '../protos/protos';
import * as assert from 'assert';
import { describe, it } from 'mocha';
/* eslint-disable @typescript-eslint/no-var-requires */
const metricsservicev2Module = require('../src');


const FAKE_STATUS_CODE = 1;
class FakeError{
    name: string;
    message: string;
    code: number;
    constructor(n: number){
        this.name = 'fakeName';
        this.message = 'fake message';
        this.code = n;
    }
}
const error = new FakeError(FAKE_STATUS_CODE);
export interface Callback {
  (err: FakeError|null, response?: {} | null): void;
}

export class Operation{
    constructor(){};
    promise() {};
}
function mockSimpleGrpcMethod(expectedRequest: {}, response: {} | null, error: FakeError | null) {
    return (actualRequest: {}, options: {}, callback: Callback) => {
        assert.deepStrictEqual(actualRequest, expectedRequest);
        if (error) {
            callback(error);
        } else if (response) {
            callback(null, response);
        } else {
            callback(null);
        }
    };
}
describe('v2.MetricsServiceV2Client', () => {
    it('has servicePath', () => {
        const servicePath = metricsservicev2Module.v2.MetricsServiceV2Client.servicePath;
        assert(servicePath);
    });
    it('has apiEndpoint', () => {
        const apiEndpoint = metricsservicev2Module.v2.MetricsServiceV2Client.apiEndpoint;
        assert(apiEndpoint);
    });
    it('has port', () => {
        const port = metricsservicev2Module.v2.MetricsServiceV2Client.port;
        assert(port);
        assert(typeof port === 'number');
    });
    it('should create a client with no option', () => {
        const client = new metricsservicev2Module.v2.MetricsServiceV2Client();
        assert(client);
    });
    it('should create a client with gRPC fallback', () => {
        const client = new metricsservicev2Module.v2.MetricsServiceV2Client({
            fallback: true,
        });
        assert(client);
    });
    it('has initialize method and supports deferred initialization', async () => {
        const client = new metricsservicev2Module.v2.MetricsServiceV2Client({
            credentials: { client_email: 'bogus', private_key: 'bogus' },
            projectId: 'bogus',
        });
        assert.strictEqual(client.metricsServiceV2Stub, undefined);
        await client.initialize();
        assert(client.metricsServiceV2Stub);
    });
    it('has close method', () => {
        const client = new metricsservicev2Module.v2.MetricsServiceV2Client({
            credentials: { client_email: 'bogus', private_key: 'bogus' },
            projectId: 'bogus',
        });
        client.close();
    });
    describe('getLogMetric', () => {
        it('invokes getLogMetric without error', done => {
            const client = new metricsservicev2Module.v2.MetricsServiceV2Client({
                credentials: {client_email: 'bogus', private_key: 'bogus'},
                projectId: 'bogus',
            });
            // Initialize client before mocking
            client.initialize();
            // Mock request
            const request: protosTypes.google.logging.v2.IGetLogMetricRequest = {};
            request.metricName = '';
            // Mock response
            const expectedResponse = {};
            // Mock gRPC layer
            client._innerApiCalls.getLogMetric = mockSimpleGrpcMethod(
                request,
                expectedResponse,
                null
            );
            client.getLogMetric(request, (err: {}, response: {}) => {
                assert.ifError(err);
                assert.deepStrictEqual(response, expectedResponse);
                done();
            })
        });

        it('invokes getLogMetric with error', done => {
            const client = new metricsservicev2Module.v2.MetricsServiceV2Client({
                credentials: {client_email: 'bogus', private_key: 'bogus'},
                projectId: 'bogus',
            });
            // Initialize client before mocking
            client.initialize();
            // Mock request
            const request: protosTypes.google.logging.v2.IGetLogMetricRequest = {};
            request.metricName = '';
            // Mock gRPC layer
            client._innerApiCalls.getLogMetric = mockSimpleGrpcMethod(
                request,
                null,
                error
            );
            client.getLogMetric(request, (err: FakeError, response: {}) => {
                assert(err instanceof FakeError);
                assert.strictEqual(err.code, FAKE_STATUS_CODE);
                assert(typeof response === 'undefined');
                done();
            })
        });
    });
    describe('createLogMetric', () => {
        it('invokes createLogMetric without error', done => {
            const client = new metricsservicev2Module.v2.MetricsServiceV2Client({
                credentials: {client_email: 'bogus', private_key: 'bogus'},
                projectId: 'bogus',
            });
            // Initialize client before mocking
            client.initialize();
            // Mock request
            const request: protosTypes.google.logging.v2.ICreateLogMetricRequest = {};
            request.parent = '';
            // Mock response
            const expectedResponse = {};
            // Mock gRPC layer
            client._innerApiCalls.createLogMetric = mockSimpleGrpcMethod(
                request,
                expectedResponse,
                null
            );
            client.createLogMetric(request, (err: {}, response: {}) => {
                assert.ifError(err);
                assert.deepStrictEqual(response, expectedResponse);
                done();
            })
        });

        it('invokes createLogMetric with error', done => {
            const client = new metricsservicev2Module.v2.MetricsServiceV2Client({
                credentials: {client_email: 'bogus', private_key: 'bogus'},
                projectId: 'bogus',
            });
            // Initialize client before mocking
            client.initialize();
            // Mock request
            const request: protosTypes.google.logging.v2.ICreateLogMetricRequest = {};
            request.parent = '';
            // Mock gRPC layer
            client._innerApiCalls.createLogMetric = mockSimpleGrpcMethod(
                request,
                null,
                error
            );
            client.createLogMetric(request, (err: FakeError, response: {}) => {
                assert(err instanceof FakeError);
                assert.strictEqual(err.code, FAKE_STATUS_CODE);
                assert(typeof response === 'undefined');
                done();
            })
        });
    });
    describe('updateLogMetric', () => {
        it('invokes updateLogMetric without error', done => {
            const client = new metricsservicev2Module.v2.MetricsServiceV2Client({
                credentials: {client_email: 'bogus', private_key: 'bogus'},
                projectId: 'bogus',
            });
            // Initialize client before mocking
            client.initialize();
            // Mock request
            const request: protosTypes.google.logging.v2.IUpdateLogMetricRequest = {};
            request.metricName = '';
            // Mock response
            const expectedResponse = {};
            // Mock gRPC layer
            client._innerApiCalls.updateLogMetric = mockSimpleGrpcMethod(
                request,
                expectedResponse,
                null
            );
            client.updateLogMetric(request, (err: {}, response: {}) => {
                assert.ifError(err);
                assert.deepStrictEqual(response, expectedResponse);
                done();
            })
        });

        it('invokes updateLogMetric with error', done => {
            const client = new metricsservicev2Module.v2.MetricsServiceV2Client({
                credentials: {client_email: 'bogus', private_key: 'bogus'},
                projectId: 'bogus',
            });
            // Initialize client before mocking
            client.initialize();
            // Mock request
            const request: protosTypes.google.logging.v2.IUpdateLogMetricRequest = {};
            request.metricName = '';
            // Mock gRPC layer
            client._innerApiCalls.updateLogMetric = mockSimpleGrpcMethod(
                request,
                null,
                error
            );
            client.updateLogMetric(request, (err: FakeError, response: {}) => {
                assert(err instanceof FakeError);
                assert.strictEqual(err.code, FAKE_STATUS_CODE);
                assert(typeof response === 'undefined');
                done();
            })
        });
    });
    describe('deleteLogMetric', () => {
        it('invokes deleteLogMetric without error', done => {
            const client = new metricsservicev2Module.v2.MetricsServiceV2Client({
                credentials: {client_email: 'bogus', private_key: 'bogus'},
                projectId: 'bogus',
            });
            // Initialize client before mocking
            client.initialize();
            // Mock request
            const request: protosTypes.google.logging.v2.IDeleteLogMetricRequest = {};
            request.metricName = '';
            // Mock response
            const expectedResponse = {};
            // Mock gRPC layer
            client._innerApiCalls.deleteLogMetric = mockSimpleGrpcMethod(
                request,
                expectedResponse,
                null
            );
            client.deleteLogMetric(request, (err: {}, response: {}) => {
                assert.ifError(err);
                assert.deepStrictEqual(response, expectedResponse);
                done();
            })
        });

        it('invokes deleteLogMetric with error', done => {
            const client = new metricsservicev2Module.v2.MetricsServiceV2Client({
                credentials: {client_email: 'bogus', private_key: 'bogus'},
                projectId: 'bogus',
            });
            // Initialize client before mocking
            client.initialize();
            // Mock request
            const request: protosTypes.google.logging.v2.IDeleteLogMetricRequest = {};
            request.metricName = '';
            // Mock gRPC layer
            client._innerApiCalls.deleteLogMetric = mockSimpleGrpcMethod(
                request,
                null,
                error
            );
            client.deleteLogMetric(request, (err: FakeError, response: {}) => {
                assert(err instanceof FakeError);
                assert.strictEqual(err.code, FAKE_STATUS_CODE);
                assert(typeof response === 'undefined');
                done();
            })
        });
    });
    describe('listLogMetrics', () => {
        it('invokes listLogMetrics without error', done => {
            const client = new metricsservicev2Module.v2.MetricsServiceV2Client({
                credentials: {client_email: 'bogus', private_key: 'bogus'},
                projectId: 'bogus',
            });
            // Initialize client before mocking
            client.initialize();
            // Mock request
            const request: protosTypes.google.logging.v2.IListLogMetricsRequest = {};
            request.parent = '';
            // Mock response
            const expectedResponse = {};
            // Mock Grpc layer
            client._innerApiCalls.listLogMetrics = (actualRequest: {}, options: {}, callback: Callback) => {
                assert.deepStrictEqual(actualRequest, request);
                callback(null, expectedResponse);
            };
            client.listLogMetrics(request, (err: FakeError, response: {}) => {
                assert.ifError(err);
                assert.deepStrictEqual(response, expectedResponse);
                done();
            });
        });
    });
    describe('listLogMetricsStream', () => {
        it('invokes listLogMetricsStream without error', done => {
            const client = new metricsservicev2Module.v2.MetricsServiceV2Client({
                credentials: {client_email: 'bogus', private_key: 'bogus'},
                projectId: 'bogus',
            });
            // Initialize client before mocking
            client.initialize();
            // Mock request
            const request: protosTypes.google.logging.v2.IListLogMetricsRequest = {};
            request.parent = '';
            // Mock response
            const expectedResponse = {response: 'data'};
            // Mock Grpc layer
            client._innerApiCalls.listLogMetrics = (actualRequest: {}, options: {}, callback: Callback) => {
                assert.deepStrictEqual(actualRequest, request);
                callback(null, expectedResponse);
            };
            const stream = client.listLogMetricsStream(request, {}).on('data', (response: {}) =>{
                assert.deepStrictEqual(response, expectedResponse);
                done();
            }).on('error', (err: FakeError) => {
                done(err);
            });
            stream.write(expectedResponse);
        });
    });
});
