introduction: |-
  [Google Cloud Logging](https://cloud.google.com/logging/docs) allows you to store, search, analyze,
  monitor, and alert on log data and events from Google Cloud Platform and Amazon Web Services.

  If you require a reduced library size, an experimental, minified version of
  this library is available at [@google-cloud/logging-min](https://www.npmjs.com/package/@google-cloud/logging-min).
  Note: `logging-min` is experimental, and its feature surface is subject to
  change.
body: |-
  ## Batching Writes

  High throughput applications should avoid awaiting calls to the logger:

  ```js
  await log.write(logEntry1);
  await log.write(logEntry2);
  ```

  Rather, applications should use a _fire and forget_ approach:

  ```js
  log.write(logEntry1);
  log.write(logEntry2);
  ```

  The `@google-cloud/logging` library will handle batching and dispatching
  these log lines to the API.
